## Variant 6
$$
  (A-B^2)\cdot(2A + B)
$$
$$
    A = \begin{pmatrix}
      5 & 2 & 0 \\
      10 & 4 & 1 \\
      7 & 3 & 2 \\
    \end{pmatrix}
$$
$$
    B = \begin{pmatrix}
      3 & 6 & -1 \\
      -1 & -2 & 0 \\
      2 & 1 & 3 \\
    \end{pmatrix}
$$

In [40]:
import numpy as np
import time

def matrix_expression(A, B):
    start_time = time.time()

    C = np.dot((A - np.dot(B, B)), (2 * A + B))

    return C, time.time() - start_time

def matrix_expression_no_numpy(A, B):
    start_time = time.time()

    n = len(A[0])
    
    B_S = [[0 for _ in range(n)] for _ in range(n)]

    for i in range(n):
        for j in range(n):
            for k in range(n):
                B_S[i][j] += B[i][k] * B[k][j]
    
    F = [[0 for _ in range(n)] for _ in range(n)]

    for i in range(n):
        for j in range(n):
                F[i][j] = A[i][j] - B_S[i][j]
    
    S = [[0 for _ in range(n)] for _ in range(n)]

    for i in range(n):
        for j in range(n):
                S[i][j] = 2*A[i][j] + B[i][j]
    
    C = [[0 for _ in range(n)] for _ in range(n)]

    for i in range(n):
        for j in range(n):
            for k in range(n):
                C[i][j] += F[i][k] * S[k][j]
    
    return C, time.time() - start_time

A = np.array([[5, 2, 0], [10, 4, 1], [3, 3, 2]])
B = np.array([[3, 6, -1], [-1, -2, 0], [2, 1, 1]])

C, time_numpy = matrix_expression(A, B)

print(f"Execution time with NumPy: {time_numpy:.6f}s")
print(C)

C, time_no_numpy = matrix_expression_no_numpy(A, B)

print(f"Execution time without NumPy: {time_no_numpy:.6f}s")
print(C)

Execution time with NumPy: 0.000048s
[[  27   50   10]
 [ 257  146    1]
 [-180  -67    3]]
Execution time without NumPy: 0.000051s
[[27, 50, 10], [257, 146, 1], [-180, -67, 3]]
