## Variant 6
Task: 1, 3, 4, 6, 10, 12, 15, 17, 18

In [16]:
import numpy as np
import time
import random

1. Вводиться число n. Вивести масив розміру n×n, в
якому по діагоналі йдуть числа від 1 до n, а інші числа дорівнюють 0.

In [38]:
def create_diagonal_matrix(n):
    start_time = time.time()

    matrix = np.zeros((n, n), dtype=int)
    np.fill_diagonal(matrix, np.arange(1, n + 1))

    return matrix, time.time() - start_time

def create_diagonal_matrix_no_numpy(n):

    start_time = time.time()

    matrix = [[0 for _ in range(n)] for _ in range(n)]
    for i in range(n):
        matrix[i][i] = i + 1

    return matrix, time.time() - start_time

def task_1():
    n = int(input("Enter a number: "))

    matrix, time_numpy = create_diagonal_matrix(n)

    print(f"Execution time with NumPy: {time_numpy:.6f}s")
    if n <= 10:
        print(matrix)

    matrix, time_no_numpy = create_diagonal_matrix_no_numpy(n)

    print(f"Execution time without NumPy: {time_no_numpy:.6f}s")
    if n <= 10:
        print(matrix)

In [60]:
task_1()

Enter a number:  5


Execution time with NumPy: 0.000034s
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
Execution time without NumPy: 0.000006s
[[1, 0, 0, 0, 0], [0, 2, 0, 0, 0], [0, 0, 3, 0, 0], [0, 0, 0, 4, 0], [0, 0, 0, 0, 5]]


In [44]:
task_1()

Enter a number:  10000


Execution time with NumPy: 0.021120s
Execution time without NumPy: 3.380005s


3. Вводяться 4 числа n, m, r, c. Вивести масив розміру n×m, в якому в кожному рядку з номером r і в кожному стовпчику з номером c стоять 0, а інші елементи дорівнюють 1.

In [54]:
def create_matrix_with_zeros(n, m, r, c):
    start_time = time.time()

    matrix = np.ones((n, m), dtype=int)
    matrix[r, :] = 0
    matrix[:, c] = 0

    return matrix, time.time() - start_time

def create_matrix_with_zeros_no_numpy(n, m, r, c):
    start_time = time.time()

    matrix = [[1 for _ in range(m)] for _ in range(n)]
    for i in range(n):
        matrix[i][c] = 0
    for j in range(m):
        matrix[r][j] = 0

    return matrix, time.time() - start_time

def task_3():
    n, m, r, c = map(int, input("Enter n, m, r, c (space-separated): ").split())
    matrix, time_numpy = create_matrix_with_zeros(n, m, r, c)

    print(f"Execution time with NumPy: {time_numpy:.6f}s")
    if n <= 10 and m <= 10:
        print(matrix)

    matrix, time_no_numpy = create_matrix_with_zeros_no_numpy(n, m, r, c)

    print(f"Execution time without NumPy: {time_no_numpy:.6f}s")
    if n <= 10 and m <= 10:
        print(matrix)

In [62]:
task_3()

Enter n, m, r, c (space-separated):  6 7 2 3


Execution time with NumPy: 0.000038s
[[1 1 1 0 1 1 1]
 [1 1 1 0 1 1 1]
 [0 0 0 0 0 0 0]
 [1 1 1 0 1 1 1]
 [1 1 1 0 1 1 1]
 [1 1 1 0 1 1 1]]
Execution time without NumPy: 0.000007s
[[1, 1, 1, 0, 1, 1, 1], [1, 1, 1, 0, 1, 1, 1], [0, 0, 0, 0, 0, 0, 0], [1, 1, 1, 0, 1, 1, 1], [1, 1, 1, 0, 1, 1, 1], [1, 1, 1, 0, 1, 1, 1]]


In [64]:
task_3()

Enter n, m, r, c (space-separated):  10000 10000 420 6969


Execution time with NumPy: 1.183957s
Execution time without NumPy: 3.859102s


4. Вводяться числа n і m. Вивести масив розміру n×m, в якому у першому рядку (рядок з нулевим індексом) йдуть числа від 0 до m–1, а всі інші елементи матриці дорівнюють 0.

In [73]:
def create_matrix_with_first_row_filled(n, m):
    start_time = time.time()

    matrix = np.zeros((n, m), dtype=int)
    matrix[0, :] = np.arange(m)

    return matrix, time.time() - start_time

def create_matrix_with_first_row_filled_no_numpy(n, m):
    start_time = time.time()

    matrix = [[0 for _ in range(m)] for _ in range(n)]
    for i in range(m):
        matrix[0][i] = i

    return matrix, time.time() - start_time

def task_4():
    n, m = map(int, input("Enter n, m (space-separated): ").split())
    matrix, time_numpy = create_matrix_with_first_row_filled(n, m)

    print(f"Execution time with NumPy: {time_numpy:.6f}s")
    if n <= 10 and m <= 10:
        print(matrix)

    matrix, time_no_numpy = create_matrix_with_first_row_filled_no_numpy(n, m)

    print(f"Execution time without NumPy: {time_no_numpy:.6f}s")
    if n <= 10 and m <= 10:
        print(matrix)

In [75]:
task_4()

Enter n, m (space-separated):  3 4


Execution time with NumPy: 0.000026s
[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]
Execution time without NumPy: 0.000007s
[[0, 1, 2, 3], [0, 0, 0, 0], [0, 0, 0, 0]]


In [77]:
task_4()

Enter n, m (space-separated):  10000 9999


Execution time with NumPy: 0.000130s
Execution time without NumPy: 3.853938s


6. З клавіатури вводиться масив. Замінити всі ненульові елементи на –1.

In [87]:
def replace_non_zero_elements(array):
    start_time = time.time()

    array[array != 0] = -1

    return array, time.time() - start_time

def replace_non_zero_elements_no_numpy(array):
    start_time = time.time()

    for i in range(len(array)):
            if array[i] != 0:
                array[i] = -1

    return array, time.time() - start_time

def task_6():
    arr = list(map(int, input("Enter the array elements separated by spaces: ").split()))
    
    array, time_numpy = replace_non_zero_elements(np.array(arr))

    print(f"Execution time with NumPy: {time_numpy:.6f}s")
    print(array)

    array, time_no_numpy = replace_non_zero_elements_no_numpy(arr)

    print(f"Execution time without NumPy: {time_no_numpy:.6f}s")
    print(array)

In [89]:
task_6()

Enter the array elements separated by spaces:  1 2 3 0 4 -3 0 -650 0 20 4 0 0 0 6 0 6 0


Execution time with NumPy: 0.000026s
[-1 -1 -1  0 -1 -1  0 -1  0 -1 -1  0  0  0 -1  0 -1  0]
Execution time without NumPy: 0.000006s
[-1, -1, -1, 0, -1, -1, 0, -1, 0, -1, -1, 0, 0, 0, -1, 0, -1, 0]


10. Вводиться числа n i m. Створити масив випадкових значень n×m і обчислити мінімальне, максимальне значення, середнє та середньо квадратичне відхилення, округлене до 3 знаків після коми.

In [3]:
def calculate(array):
    start_time = time.time()

    min_value = round(np.min(array), 3)
    max_value = round(np.max(array), 3)
    avg = round(np.mean(array), 3)
    std_deviation = round(np.std(array), 3)

    return min_value, max_value, avg, std_deviation, time.time() - start_time

def calculate_no_numpay(array):
    start_time = time.time()
    
    flat_array = [value for sublist in array for value in sublist]

    min_value = round(min(flat_array), 3)
    max_value = round(max(flat_array), 3)
    avg = round(sum(flat_array) / len(flat_array), 3)

    mean_value = sum(flat_array) / len(flat_array)
    std_deviation = round((sum((x - mean_value) ** 2 for x in flat_array) / len(flat_array)) ** 0.5, 3)

    return min_value, max_value, avg, std_deviation, time.time() - start_time

def task_10():
    n, m = map(int, input("Enter n, m (space-separated): ").split())
    
    random_array = np.random.rand(n, m)
    if n <= 10 and m <= 10:
        print(random_array)

    min_v, max_v, avg, std, time_numpy = calculate(random_array)
    print(f"Execution time with NumPy: {time_numpy:.6f}s")
    print(f"min: {min_v}, max: {max_v}, average: {avg}, std deviation: {std}")

    min_v, max_v, avg, std, time_no_numpy = calculate_no_numpay(random_array)

    print(f"Execution time without NumPy: {time_no_numpy:.6f}s")
    print(f"min: {min_v}, max: {max_v}, average: {avg}, std deviation: {std}")

In [102]:
task_10()

Enter n, m (space-separated):  4 5


[[0.10466667 0.40184422 0.82646469 0.24516337 0.79959296]
 [0.9299331  0.37135503 0.28581217 0.34855892 0.55701094]
 [0.33790979 0.13354559 0.97306975 0.77853137 0.2032729 ]
 [0.25126273 0.31419556 0.96993273 0.08247369 0.00977556]]
Execution time with NumPy: 0.000171s
min: 0.01, max: 0.973, average: 0.446, std deviation: 0.31
Execution time without NumPy: 0.000053s
min: 0.01, max: 0.973, average: 0.446, std deviation: 0.31


In [11]:
task_10()

Enter n, m (space-separated):  5000 7000


Execution time with NumPy: 0.300327s
min: 0.0, max: 1.0, average: 0.5, std deviation: 0.289
Execution time without NumPy: 13.940190s
min: 0.0, max: 1.0, average: 0.5, std deviation: 0.289


12. Створити масив одиниць розміром n×n та створити в ньому «рамку», що утворюється з 0.

In [26]:
def create_ones_matrix_with_zeros_frame(n):
    start_time = time.time()

    matrix = np.ones((n, n), dtype=int)
    
    matrix[0, :] = 0
    matrix[:, 0] = 0
    matrix[-1, :] = 0
    matrix[:, -1] = 0

    return matrix, time.time() - start_time

def create_ones_matrix_with_zeros_frame_no_numpay(n):
    start_time = time.time()
    
    matrix = [[1 for _ in range(n)] for _ in range(n)]

    for i in range(n):
        matrix[0][i] = 0
        matrix[i][0] = 0
        matrix[-1][i] = 0
        matrix[i][-1] = 0 

    return matrix, time.time() - start_time

def task_12():
    n = int(input("Enter n: "))

    array, time_numpy = create_ones_matrix_with_zeros_frame(n)
    print(f"Execution time with NumPy: {time_numpy:.6f}s")
    if n <= 10:
        print(array)

    array, time_no_numpy = create_ones_matrix_with_zeros_frame_no_numpay(n)

    print(f"Execution time without NumPy: {time_no_numpy:.6f}s")
    if n <= 10:
        print(array)

In [24]:
task_12()

Enter n:  4


Execution time with NumPy: 0.000048s
[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]
Execution time without NumPy: 0.000009s
[[0, 0, 0, 0], [0, 1, 1, 0], [0, 1, 1, 0], [0, 0, 0, 0]]


In [28]:
task_12()

Enter n:  10000


Execution time with NumPy: 0.252616s
Execution time without NumPy: 3.665191s


15. Заповнити парні стовпчикі матриці розміром n×n одиницями, а непарні – нулями.

In [31]:
def create_matrix_with_even_columns_ones_odd_zeros(n):
    start_time = time.time()

    matrix = np.zeros((n, n), dtype=int)
    matrix[:, 1::2] = 1

    return matrix, time.time() - start_time

def create_matrix_with_even_columns_ones_odd_zeros_no_numpay(n):
    start_time = time.time()
    
    matrix = [[0] * n for _ in range(n)]

    for i in range(n):
        for j in range(1, n, 2):
            matrix[i][j] = 1


    return matrix, time.time() - start_time

def task_15():
    n = int(input("Enter n: "))

    array, time_numpy = create_matrix_with_even_columns_ones_odd_zeros(n)
    print(f"Execution time with NumPy: {time_numpy:.6f}s")
    if n <= 10:
        print(array)

    array, time_no_numpy = create_matrix_with_even_columns_ones_odd_zeros_no_numpay(n)

    print(f"Execution time without NumPy: {time_no_numpy:.6f}s")
    if n <= 10:
        print(array)

In [33]:
task_15()

Enter n:  5


Execution time with NumPy: 0.000019s
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Execution time without NumPy: 0.000008s
[[0, 1, 0, 1, 0], [0, 1, 0, 1, 0], [0, 1, 0, 1, 0], [0, 1, 0, 1, 0], [0, 1, 0, 1, 0]]


In [35]:
task_15()

Enter n:  10000


Execution time with NumPy: 0.422667s
Execution time without NumPy: 2.676821s


17. Заповнити вектор значеннями від 0 до n. Замінити знаки для всіх значень, що менші за n/2 та більші за 3n/4 на протилежні.

In [7]:
def calculate_vector(n):
    start_time = time.time()

    vector = np.arange(n)

    vector[(vector < n/2) | (vector > 3*n/4)] *= -1

    return vector, time.time() - start_time

def calculate_vector_no_numpay(n):
    start_time = time.time()
    
    vector = [i if n/2 <= i <= 3*n/4 else -i for i in range(n)]

    return vector, time.time() - start_time

def task_17():
    n = int(input("Enter n: "))

    vector, time_numpy = calculate_vector(n)
    print(f"Execution time with NumPy: {time_numpy:.6f}s")
    if n <= 10:
        print(vector)

    vector, time_no_numpy = calculate_vector_no_numpay(n)

    print(f"Execution time without NumPy: {time_no_numpy:.6f}s")
    if n <= 10:
        print(vector)

In [40]:
task_17()

Enter n:  10


Execution time with NumPy: 0.000121s
[ 0 -1 -2 -3 -4  5  6  7 -8 -9]
Execution time without NumPy: 0.000007s
[0, -1, -2, -3, -4, 5, 6, 7, -8, -9]


In [9]:
task_17()

Enter n:  10000000


Execution time with NumPy: 0.114012s
Execution time without NumPy: 1.483384s


18. Згенерувати вектор з n випадкових чисел в діапазоні від 0 до 99. Визначити кількість унікальних чисел в послідовності.

In [24]:
def get_unique_numbers(n):
    start_time = time.time()

    vector = np.random.randint(0, 100, n)
    unique_numbers = np.unique(vector).size

    end_time = time.time()

    return vector, unique_numbers, end_time - start_time

def get_unique_numbers_no_numpy(n):
    start_time = time.time()

    vector = []
    for _ in range(n):
        vector.append(random.randint(0, 99))
    unique_numbers = len(set(vector))

    end_time = time.time()

    return vector, unique_numbers, end_time - start_time

def task_18():
    n = int(input("Enter n: "))

    vector, cu, time_numpy = get_unique_numbers(n)
    print(f"Execution time with NumPy: {time_numpy:.6f}s")
    if n <= 10:
        print(vector)
    print(cu)

    vector, cu, time_no_numpy = get_unique_numbers_no_numpy(n)

    print(f"Execution time without NumPy: {time_no_numpy:.6f}s")
    if n <= 10:
        print(vector)
    print(cu)

In [32]:
task_18()

Enter n:  10


Execution time with NumPy: 0.000115s
[85 45 26 24 12 67 62 67 32  5]
9
Execution time without NumPy: 0.000013s
[17, 85, 67, 40, 67, 16, 78, 84, 47, 40]
8


In [28]:
task_18()

Enter n:  100000


Execution time with NumPy: 0.004856s
100
Execution time without NumPy: 0.048047s
100
